version: "3.9"

services:
  famadi-demo:
    image: nginx:alpine
    container_name: famadi-demo
    restart: always
    volumes:
      - ./src:/usr/share/nginx/html:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.famadi-demo.rule=Host(`famadi-demo.paketartes.com`)"
      - "traefik.http.routers.famadi-demo.entrypoints=websecure"
      - "traefik.http.routers.famadi-demo.tls.certresolver=letsencrypt"
      - "traefik.http.services.famadi-demo.loadbalancer.server.port=80"
    networks:
      - traefik

networks:
  traefik:
    external: true
