version: "3.9"

services:
  showroom:
    image: nginx:alpine
    container_name: famadi-showroom
    restart: always

    volumes:
      - /home/ubuntu/famadi-showroom/src:/usr/share/nginx/html:ro

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.showroom.rule=Host(`famadi-demo.paketartes.com`)"
      - "traefik.http.routers.showroom.entrypoints=websecure"
      - "traefik.http.routers.showroom.tls.certresolver=letsencrypt"

    networks:
      - traefik

networks:
  traefik:
    external: true
