version: "3.9"

services:
  showroom:
    image: nginx:alpine
    container_name: famadi-demo
    restart: always

    volumes:
      - /home/ubuntu/famadi-demo/:/usr/share/nginx/html:ro

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.showroom-famadi.rule=Host(`famadi-demo.paketartes.com`)"
      - "traefik.http.routers.showroom-famadi.entrypoints=websecure"
      - "traefik.http.routers.showroo-famadi.tls.certresolver=letsencrypt"

    networks:
      - traefik

networks:
  traefik:
    external: true
